# Generated by Django 2.0.6 on 2018-06-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.DateField(auto_now_add=True)),
                ('min_weight', models.IntegerField(default=0)),
                ('max_weight', models.IntegerField(default=0)),
                ('variance', models.IntegerField(default=0)),
            ],
        ),
    ]
